### numpy

In [6]:
import numpy as np

#creating array using numpy
arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2] ,[3,4]])
print(arr)
print(arr2)
print(type(arr))
print(type(arr2))
print(arr.shape)
print(arr2.shape)

#shape agar ek number aaya means 1-D array h or agar do toh 2-D array hai


[1 2 3 4 5]
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(5,)
(2, 2)


### numpy ones and zeros

In [1]:
import numpy as np

arr = np.ones((3,4))
print(arr)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
arr1 = np.zeros((4,6))
print(arr1)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


### Identity Matrix

In [4]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Vectorised OPerations in NumPy

In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#Elemnet wise operations 

print("Addition : " ,arr1+arr2)
print("Subtraction : " ,arr1-arr2)
print("Multiplication : " ,arr1*arr2)
print("Division : " ,arr1/arr2)



Addition :  [11 22 33 44 55]
Subtraction :  [ -9 -18 -27 -36 -45]
Multiplication :  [ 10  40  90 160 250]
Division :  [0.1 0.1 0.1 0.1 0.1]
